baseURL = "http://whoisthisjoker.com"
languageCode = "en-us"
title = "C:/WhoIsThisJoker"
theme = "my-theme"
paginate = 5

copyright = "©Daniel Redd Jones"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	subtitle = "Are lobsters scorpion mermaids?"

	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "light"

	# Enable a table of contents:
	# Either "static"/true, "floating", "both", or "none" (default: static)
	# The floating TOC dissapears on mobile and adds 200px vertical space
	toc = "both"
	# Whether to truncate everything but H1/H2 headings if the last element in a TOC isn't visible. Enabled by default
	enableTocTrunate = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	footers = [ 
		"Now may the God of peace Himself sanctify you entirely; and may your spirit and soul and body be kept complete, without blame at the coming of our Lord Jesus Christ. ~1 Thessalonians 5:23"
	]

		

	# For statistics, we can compare the total word count against a book of your choice
	statisticsEnabled = false
	referenceBookWords = 56750.0
	referenceBook = "Mere Christianity"
	referenceAuthor = "C.S. Lewis"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Fun Links"
url = "/jokerlinks"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Code"
url = "https://git.whoisthisjoker.com/Daniel"
weight = 5

[[menu.main]]
name = "RSS"
url = "/post/index.xml"
weight = 6

[[menu.main]]
name = "CV"
url = "https://danielreddjones.com"
weight = 7

[[menu.main]]
name = "Tags & Stats"
url = "/tags"
weight = 8

[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
