baseURL = "http://whoisthisjoker.com"
languageCode = "en-us"
title = "C:\\WhoIsThisJoker"
theme = "cyberscape"
paginate = 5
features = ["markdown", "tailwind"]

copyright = "©Daniel Redd Jones"
# Demo only
#ignoreErrors = ["error-missing-instagram-accesstoken"]

[permalinks]
  posts = "/:year/:month/:title"

[params]
	favicon = "/profile.png"
	subtitle = "Centaurs have two ribcages"

	# Optional 64x64 avatar image.
	 avatar = "/profile.png"

	featherIconsCDN = false

	# Site color - dark/light/auto
	mode = "light"

	# Enable a table of contents:
	# Either "static"/true, "floating", "both", or "none" (default: static)
	# The floating TOC dissapears on mobile and adds 200px vertical space
	toc = "both"
	# Whether to truncate everything but H1/H2 headings if the last element in a TOC isn't visible. Enabled by default
	enableTocTrunate = true

	# Max tags
	maxTags = 7

	# Define words per minute to approximate reading time
	wpm = 250

	footers = [ 
		"Now may the God of peace Himself sanctify you entirely; and may your spirit and soul and body be kept complete, without blame at the coming of our Lord Jesus Christ. ~1 Thessalonians 5:23"
	]

		

# Nav.


[[menu.main]]
name = "blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Funlinks"
url = "/jokerlinks/list"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Code"
url = "http://gitea.whoisthisjoker.com"
weight = 5

[[menu.main]]
name = "RSS"
url = "/post/index.xml"
weight = 6

[[menu.main]]
name = "CV"
url = "https://danielreddjones.com"
weight = 7

[[menu.main]]
name = "Projects"
url = "/projects/projects"
weight = 8




[taxonomies]
   tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2 
